Create artado.json
is-not-cool/registration pull request #41
Opened 2024-11-22 17:59 UTC by Sxinar

2024-11-24 18:09 UTC, CuteDog5695 requested changes
Why do you need NS records?

2024-11-24 18:09 UTC, CuteDog5695 requested changes
Missed these ones, anyways

2024-11-24 18:09 UTC, CuteDog5695 commented on domains/artado.json
> +        "email": "oshidev@proton.me",
```suggestion
        "email": "oshidev@proton.me"
```

2024-11-24 18:09 UTC, CuteDog5695 commented on domains/artado.json
> +        "NS": ["ns1.byet.org , ns2.byet.org , ns3.byet.org , ns4.byet.org , ns5.byet.org"],
```suggestion
        "NS": ["ns1.byet.org , ns2.byet.org , ns3.byet.org , ns4.byet.org , ns5.byet.org"]
```

2024-11-28 18:42 UTC, CuteDog5695 commented
Can't you do it via CNAME? Or am I wrong? (As far as I remember, its possible without NS records)

2024-11-28 18:47 UTC, Sxinar commented
> Can't you do it via CNAME? Or am I wrong? (As far as I remember, its possible without NS records)

Yeah İTS possible because i want to vistapanel cname errors (i dont have screenshot) Ns better than

(İ have A very lazy English i am sorry)

2024-11-30 18:47 UTC, CuteDog5695 approved these changes
I guess you can have NS records then.... (Its for the reason earlier, not for the last comment)

2024-11-30 18:49 UTC, CuteDog5695 approved these changes

2024-11-30 18:50 UTC, merged