Create ai.json
is-not-cool/registration pull request #49
Opened 2024-12-31 20:06 UTC by ramanandkrgupta

2024-12-31 20:08 UTC, iostpa requested changes

2024-12-31 20:08 UTC, iostpa commented on domains/ai.json
> +        "NS": ["aron.ns.cloudflare.com", "decker.ns.cloudflare.com"],
You can't use Cloudflare DNS with our domain, since we aren't in the Public Suffix List (PSL) yet.

2025-01-09 16:28 UTC, trollmeight commented on domains/ai.json
> +        "NS": ["aron.ns.cloudflare.com", "decker.ns.cloudflare.com"],
indeed, 
(iostpa im being held hostage to not put it on psl trust)

2025-01-11 17:00 UTC, iostpa commented
Closing due to inactivity.

2025-01-11 17:00 UTC, closed without merging